###
GET http://localhost:8080/organization/activities/list
Authorization: Basic Organization1 Coding12#

###
GET http://localhost:8080/organization/activities/list
Authorization: Basic Organization2 Coding12#

###
GET http://localhost:8080/organization/activities/list
Authorization: Basic Organization3 Coding12#

###
GET http://localhost:8080/individual/activities/list
Authorization: Basic Individual1 Coding12#

###
GET http://localhost:8080/individual/activities/list
Authorization: Basic Individual2 Coding12#

###
GET http://localhost:8080/individual/activities/list
Authorization: Basic Individual3 Coding12#

###
GET http://localhost:8080/volunteer/activities/view
Authorization: Basic Volunteer1 Coding12#