### Register for Email Notification Daily/Weekly/Monthly
PUT http://localhost:8080/volunteer/activities/email/cook/DAILY
Authorization: Basic Hansel Coding12#

### Register for Email Notification Daily/Weekly/Monthly
PUT http://localhost:8080/volunteer/activities/email/bike/weekly
Authorization: Basic Hansel Coding12#

### Register for Email Notification Daily/Weekly/Monthly
PUT http://localhost:8080/volunteer/activities/email/pilot/MONTHLY
Authorization: Basic Hansel Coding12#

### View registered Email Notifications Daily/Weekly/Monthly
GET http://localhost:8080/volunteer/activities/email/keywords
Authorization: Basic Hansel Coding12#

### Delete Email Notification Daily/Weekly/Monthly
DELETE http://localhost:8080/volunteer/activities/email/cook/delete
Authorization: Basic Hansel Coding12#

### Test request for daily Email notifications
GET http://localhost:8080/users/notifications/email/test/daily
Authorization: Basic admin Coding12#