### Send forgotten password link
GET http://localhost:8080/users/passwordreset/melanie.huetterer@gmail.com

### Set a new password
POST http://localhost:8080/users/passwordreset/melanie.huetterer@gmail.com/d1108340-1451-4238-9886-fde4549a7f2a
Content-Type: text/plain

Password12#

### View own profile as seen by others, only mandatory info -FAIL
GET http://localhost:8080/volunteer/view
Authorization: Basic Volunteer1 Coding12#

### View own profile as seen by others, only mandatory info -FAIL
GET http://localhost:8080/volunteer/view
Authorization: Basic Volunteer1 Password12#