##### Registration for e-mail notifications #####

### Add new user - valid email!!!
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "Meli",
  "password": "Coding12#",
  "role": "ROLE_VOLUNTEER",
  "fullName": "Test",
  "birthday": null,
  "address": null,
  "email": "xxx@gmail.com",
  "description": null
}

### Add some notifications to new user

### Contact a volunteer as an organization- to get notification
PUT http://localhost:8080/organization/activities/contact/2/Meli
Authorization: Basic Organization1 Coding12#

### Contact a volunteer as an organization- to get notification
PUT http://localhost:8080/organization/activities/contact/4/Meli
Authorization: Basic Organization2 Coding12#

### Contact a volunteer as an individual- to get notification
PUT http://localhost:8080/individual/activities/contact/14/Meli
Authorization: Basic MisterW Coding12#


### View notifications from profile
GET http://localhost:8080/users/notifications
Authorization: Basic Meli Coding12#



### Register for email notification
PUT http://localhost:8080/users/notifications/email/weekly
Authorization: Basic Meli Coding12#

### View details of user account- to show successfull registration
GET http://localhost:8080/admin/account/Meli
Authorization: Basic admin Coding12#

### Trigger email notification
GET http://localhost:8080/users/notifications/email/test/Meli
Authorization: Basic admin Coding12#


##### Unsubscribe option in email of notifications #####

### Click link to unsubscribe in email - show changed email notification status
### Note: Maybe Chrome wants you to type in username and password

### View details of user account
GET http://localhost:8080/admin/account/Meli
Authorization: Basic admin Coding12#