#################################### Filter Volunteer ####################################

### Filter Volunteer for Skills as Organization - cook
GET http://localhost:8080/organization/search/filter/volunteers/o
Authorization: Basic Organization1 Coding12#
Content-Type: application/json

{
   "skills": "cook"
}

### Filter Volunteer for Rating as Organization - 3 and above
GET http://localhost:8080/organization/search/filter/volunteers/o
Authorization: Basic Organization1 Coding12#
Content-Type: application/json

{
  "rating": "3"
}

### Filter Volunteer for Skills and Rating as Organization - cook, 3 and above
GET http://localhost:8080/organization/search/filter/volunteers/o
Authorization: Basic Organization1 Coding12#
Content-Type: application/json

{
  "skills": "cook",
  "rating": "3"
}

### Filter Volunteer for Skills and Rating as Organization - pilot, 4 and above / FAIL
GET http://localhost:8080/organization/search/filter/volunteers/o
Authorization: Basic Organization1 Coding12#
Content-Type: application/json

{
  "skills": "pilot",
  "rating": "4"
}

### Filter Volunteer for Skills and Rating as Individual - cook, 3 and above
GET http://localhost:8080/individual/search/filter/volunteers/o
Authorization: Basic Granny Coding12#
Content-Type: application/json

{
  "skills": "baking",
  "rating": "2"
}

### Filter Volunteer for Skills and Rating as Individual - pilot, 4 and above / FAIL
GET http://localhost:8080/individual/search/filter/volunteers/o
Authorization: Basic Granny Coding12#
Content-Type: application/json

{
  "skills": "pilot",
  "rating": "4"
}


#################################### Filter Activity ####################################

### Filter Activity for Date as Volunteer - Date 2020-01-22
GET http://localhost:8080/volunteer/activities/search/filtered/o
Authorization: Basic Derek Coding12#
Content-Type: application/json

{
  "date": "2020-01-22"
}

### Filter Activity for Category as Volunteer - Category cooking
GET http://localhost:8080/volunteer/activities/search/filtered/o
Authorization: Basic Derek Coding12#
Content-Type: application/json

{
  "category": "cooking"
}

### Filter Activity for Skills as Volunteer - Skills baking
GET http://localhost:8080/volunteer/activities/search/filtered/o
Authorization: Basic Derek Coding12#
Content-Type: application/json

{
  "skills": "baking"
}

### Filter Activity for Creator as Volunteer - Creator Organization3
GET http://localhost:8080/volunteer/activities/search/filtered/o
Authorization: Basic Derek Coding12#
Content-Type: application/json

{
  "creator": "Organization3"
}

### Filter Activity for Rating as Volunteer - Rating 2 or above
GET http://localhost:8080/volunteer/activities/search/filtered/o
Authorization: Basic Derek Coding12#
Content-Type: application/json

{
  "rating": "4"
}

### Filter Activity as Volunteer
GET http://localhost:8080/volunteer/activities/search/filtered/o
Authorization: Basic Derek Coding12#
Content-Type: application/json

{
  "date": "2020-01-18",
  "category": "kitchen",
  "skills": "cooking",
  "creator": "Organization3",
  "rating": "2"
}

### Filter Activity as Volunteer / FAIL
GET http://localhost:8080/volunteer/activities/search/filtered/o
Authorization: Basic Derek Coding12#
Content-Type: application/json

{
  "date": "2020-01-19",
  "category": "transport",
  "skills": "endurance",
  "creator": "Individual4",
  "rating": "5"
}

#################################### Edit Posted Activity ####################################

### List all own activities as organization
GET http://localhost:8080/organization/activities/list
Authorization: Basic Organization1 Coding12#

### list all pending activities as volunteer
GET http://localhost:8080/volunteer/activities/list/pending
Authorization: Basic Derek Coding12#

### apply for an activity as a volunteer
PUT http://localhost:8080/volunteer/activities/apply/1
Authorization: Basic Derek Coding12#

### view all notifications
GET http://localhost:8080/users/notifications
Authorization: Basic Organization1 Coding12#

### list all pending activities as volunteer
GET http://localhost:8080/volunteer/activities/list
Authorization: Basic Derek Coding12#

### edit activity as organization
PUT http://localhost:8080/organization/activities/edit/1
Authorization: Basic Organization1 Coding12#
Content-Type: application/json

{
  "creator": "Organization1",
  "title": "Activity 1 of Org1",
  "description": "Posted and edited of Org1",
  "recommendedSkills": "cooking;eating",
  "categories": "food",
  "startTime": "2020-01-16T00:00:00",
  "endTime": "2050-01-19T00:00:00",
  "statusClient": "PENDING"
}

### view all notifications
GET http://localhost:8080/users/notifications
Authorization: Basic Derek Coding12#

#################################### Delete Potsed Activity ####################################

### List all own activities as individual
GET http://localhost:8080/individual/activities/list
Authorization: Basic MisterW Coding12#

### list all pending activities as volunteer
GET http://localhost:8080/volunteer/activities/list/pending
Authorization: Basic Hansel Coding12#

### apply for an activity as a volunteer
PUT http://localhost:8080/volunteer/activities/apply/13
Authorization: Basic Hansel Coding12#

### view all notifications
GET http://localhost:8080/users/notifications
Authorization: Basic MisterW Coding12#

### list all pending activities as volunteer
GET http://localhost:8080/volunteer/activities/list
Authorization: Basic Hansel Coding12#

### delete activity as individual
DELETE http://localhost:8080/individual/activities/delete/13
Authorization: Basic MisterW Coding12#

### view all notifications
GET http://localhost:8080/users/notifications
Authorization: Basic Hansel Coding12#

#################################### Discard Activity Draft ####################################

### List all own drafts as organization
GET http://localhost:8080/organization/activities/list/drafts
Authorization: Basic Organization2 Coding12#

### delete activity as organization
DELETE http://localhost:8080/organization/activities/delete/6
Authorization: Basic Organization2 Coding12#