### Invalid Password
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "LeSchoki",
  "password": "invalidPassword",
  "role": "ROLE_VOLUNTEER",
  "fullName": "Georg Soher",
  "birthday": null,
  "address": null,
  "email": "georg.soher@bugbusters.com",
  "description": null
}

### Missing FullName
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "LeSchoki",
  "password": "Coding12#",
  "role": "ROLE_VOLUNTEER",
  "fullName": null,
  "birthday": null,
  "address": null,
  "email": "georg.soher@bugbusters.com",
  "description": null
}

### Invalid Email
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "LeSchoki",
  "password": "invalidPassword",
  "role": "ROLE_VOLUNTEER",
  "fullName": "Georg Soher",
  "birthday": null,
  "address": null,
  "email": "totallyValidEmail",
  "description": null
}

### Valid Post with only mandatory info
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "LeSchoki",
  "password": "Coding12#",
  "role": "ROLE_VOLUNTEER",
  "fullName": "Georg Soher",
  "birthday": null,
  "address": null,
  "email": "georg.soher@bugbusters.com",
  "description": null
}

### Valid Post with optional info
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "Tester",
  "password": "Coding12#",
  "role": "ROLE_INDIVIDUAL",
  "fullName": "Test Testington",
  "birthday": "1990-01-01",
  "address": "Teststreet 5, Testville, Tennessee",
  "email": "test.testington@bugbusters.com",
  "description": "Tester that tests"
}

### Valid Post for organization
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "BigO",
  "password": "Coding12#",
  "role": "ROLE_ORGANIZATION",
  "fullName": "Big Organization",
  "birthday": null,
  "address": null,
  "email": "big.o@bo.com",
  "description": null
}

### Valid Post with only mandatory info
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "Meli",
  "password": "Coding12#",
  "role": "ROLE_VOLUNTEER",
  "fullName": "Melanie",
  "birthday": null,
  "address": null,
  "email": "melanie.huett@bugbusters.com",
  "description": null
}

### View own account data
GET http://localhost:8080/volunteer/login
Authorization: Basic LeSchoki Coding12#

### View own profile as seen by others, with optional info and rating
GET http://localhost:8080/volunteer/view
Authorization: Basic LeSchoki Coding12#

### View own profile as seen by others, only mandatory info
GET http://localhost:8080/volunteer/view
Authorization: Basic Meli Coding12#

### View other profile with full info
GET http://localhost:8080/volunteer/view/Tester
Authorization: Basic LeSchoki Coding12#

### View other profile with only mandatory info
GET http://localhost:8080/volunteer/view/BigO
Authorization: Basic LeSchoki Coding12#

### View other volunteer as volunteer (FAIL)
GET http://localhost:8080/volunteer/view/LeSchoki
Authorization: Basic Meli Coding12#

### View volunteer as organization
GET http://localhost:8080/organization/view/LeSchoki
Authorization: Basic BigO Coding12#

### View volunteer as individual
GET http://localhost:8080/individual/view/LeSchoki
Authorization: Basic Tester Coding12#

### View organization as individual (FAIL)
GET http://localhost:8080/individual/view/BigO
Authorization: Basic Tester Coding12#

### contacting wrong endpoint
GET http://localhost:8080/volunteer/login
Authorization: Basic Tester Coding12#

### contacting correct endpoint
GET http://localhost:8080/individual/login
Authorization: Basic Tester Coding12#

### Valid volunteer changes
PUT http://localhost:8080/volunteer/edit
Authorization: Basic LeSchoki Coding12#
Content-Type: application/json

{
  "user": {
    "username": "LeSchoki",
    "role": "ROLE_VOLUNTEER",
    "fullName": "Georg Soher",
    "birthday": "1993-03-11",
    "address": null,
    "email": "georg.soher@bugbusters.com",
    "description": "This description is added later on"
  },
  "skills": "cooking;testing;a lot of laughing"
}

### Invalid volunteer email change
PUT http://localhost:8080/volunteer/edit
Authorization: Basic LeSchoki Coding12#
Content-Type: application/json

{
  "user": {
    "username": "LeSchoki",
    "role": "ROLE_VOLUNTEER",
    "fullName": "Georg Soher",
    "birthday": "1993-03-11",
    "address": null,
    "email": "totallyValidEmail",
    "description": "This description is added later on"
  },
  "skills": "cooking;testing;a lot of laughing"
}

### Volunteer web app tree
GET http://localhost:8080/volunteer/webapptree
Authorization: Basic LeSchoki Coding12#

### Organization web app tree
GET http://localhost:8080/organization/webapptree
Authorization: Basic BigO Coding12#

### Individual web app tree
GET http://localhost:8080/individual/webapptree
Authorization: Basic Tester Coding12#

### Individual can see all volunteers
GET http://localhost:8080/individual/view/volunteers
Authorization: Basic Tester Coding12#

### Meli is better match than LeSchoki
GET http://localhost:8080/individual/search/e
Authorization: Basic Tester Coding12#

### Description match
GET http://localhost:8080/individual/search/description
Authorization: Basic Tester Coding12#

### Org can see all volunteers
GET http://localhost:8080/organization/view/volunteers
Authorization: Basic BigO Coding12#

### LeSchoki only match, case insensitive
GET http://localhost:8080/organization/search/les
Authorization: Basic BigO Coding12#