spring:
  datasource:
    url: jdbc:mysql://localhost/user-db?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
webapptree:
  volunteer: "Edit own profile \nView own public profile \nView Organization/Individual profile"
  individual: "Edit own profile \nView own public profile \nView Volunteer profile"
  organization: "Edit own profile \nView own public profile \nView Volunteer profile"