spring:
  datasource:
    url: jdbc:mysql://localhost/user-db?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: bugbusters21@gmail.com
    password: kgatvfvoxznoyxsx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
webapptree:
  volunteer: "Edit own profile \nView own public profile \nView Organization/Individual profile\nSee all available activities\nSearch for an Activity by text\nApply for an Activity\nView own activities\nApprove an Activity\nDeny an Activity\nComplete an Activity, rate the Creator and leave feedback"
  individual: "Edit own profile \nView own public profile \nView Volunteer profile \nView list of all volunteers \nSearch for volunteers \nCreate new Activity\nSave Activity as Draft\nPost draft\nEdit an Activity\nList my Activities\nList my Drafts\nContact a Volunteer about an Activity\nApprove a Volunteer for an Activity\nDeny Volunteer for an Activity\nComplete an Activity, rate the Volunteer and leave feedback"
  organization: "Edit own profile \nView own public profile \nView Volunteer profile \nView list of all volunteers \nSearch for volunteers \nCreate new Activity\nSave Activity as Draft\nPost draft\nEdit an Activity\nList my Activities\nList my Drafts\nContact a Volunteer about an Activity\nApprove a Volunteer for an Activity\nDeny Volunteer for an Activity\nComplete an Activity, rate the Volunteer and leave feedback"
